owner: GhostCircuit-X0  # Your GitHub organization or username, where this repository lives
repo: Uptime-Status     # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # If you don’t have a custom domain, use baseUrl as below
  baseUrl: /Uptime-Status
  name: Uptime Status

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Uptime Status** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a live status page using **real-time** data from our [GitHub repository](https://github.com/GhostCircuit-X0/Uptime-Status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/GhostCircuit-X0/Uptime-Status

# For more options, see https://upptime.js.org/docs/configuration
